global:
  sendAnonymousUsage: false

api:
  dashboard: true
  insecure: true

log:
  level: DEBUG
  format: common

providers:
  docker:
    endpoint: unix:///var/run/docker.sock
    watch: true
    exposedbydefault: false

  file:
    filename: /etc/traefik/dynamic.yaml
    watch: true

entryPoints:
  web:
    address: ':80'
    http:
      redirections:
        entryPoint:
          to: web_secure
          scheme: https

  web_secure:
    address: ':443'